export const GENRES = [
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Historical Fiction",
  "Horror",
  "Young Adult",
  "Dystopian",
  "Adventure",
  "Paranormal",
  "Contemporary",
  "Literary Fiction",
  "Non-Fiction",
  "Biography",
  "Self-Help",
  "Memoir",
  "Humor",
  "Graphic Novel",
  "Classic",
];
